# Generated by Django 5.0.6 on 2024-06-20 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Ecuaciones',
            fields=[
                ('id_ecuacion', models.AutoField(primary_key=True, serialize=False)),
                ('ecuacion', models.CharField(max_length=200)),
                ('ecuacion_simplificada', models.CharField(max_length=200, null=True)),
                ('xi_ecuacion', models.CharField(max_length=200, null=True)),
                ('fi_ecuacion', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Euler',
            fields=[
                ('id_ecu', models.AutoField(primary_key=True, serialize=False)),
                ('ecuacion', models.CharField(max_length=200)),
                ('h', models.CharField(max_length=200)),
                ('s', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
