# Generated by Django 5.0.6 on 2024-06-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_calculadora_app', '0002_alter_tbl_ecuaciones_user_alter_tbl_euler_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_euler',
            name='resultado',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
